[build]
builder = "nixpacks"
buildCommand = "pip install --upgrade pip && pip install -r requirements.txt"

[deploy]
startCommand = "python bot.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
PYTHON_VERSION = "3.10.0"
PYTHONUNBUFFERED = "1"
LOG_LEVEL = "INFO"
PYTHONPATH = "/app"

[[deploy.env]]
name = "DATABASE_URL"
value = "postgresql://postgres:postgres@localhost:5432/railway" 