[build]
builder = "nixpacks"
buildCommand = "pip install --upgrade pip && pip install -r requirements.txt"

[deploy]
startCommand = "flask db upgrade && python bot.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
PYTHON_VERSION = "3.12.0"
PYTHONUNBUFFERED = "1"
LOG_LEVEL = "INFO"
PYTHONPATH = "/app"
PYTHONHASHSEED = "random"
PYTHONIOENCODING = "utf-8"
PYTHONASYNCIODEBUG = "1"
PYTHONTRACEMALLOC = "1"
PYTHONFAULTHANDLER = "1"
PORT = "8000"
DATABASE_URL = "postgresql://postgres:postgres@localhost:5432/railway" 