services:
  - type: web
    name: pixel-time-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        value: https://pixel-time-tracker.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: pixel_tracker_db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0

databases:
  - name: pixel_tracker_db
    databaseName: pixel_tracker
    user: pixel_tracker_user
    plan: free 